/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.wall_1.geometry} material={nodes.wall_1.material} position={[13, -0.099, 0.982]} />
      <mesh geometry={nodes.planeGround.geometry} material={nodes.planeGround.material} position={[1, 0, -2]} />
      <mesh geometry={nodes.nWall.geometry} material={nodes.nWall.material} position={[5, 0, -2]} />
      <mesh geometry={nodes.ndecor2.geometry} material={nodes.ndecor2.material} position={[3, 0.02, -2]} />
      <mesh geometry={nodes.player1.geometry} material={nodes.player1.material} position={[0, 1, 0]}>
        <mesh geometry={nodes.player1Gun.geometry} material={nodes.player1Gun.material} position={[0.298, 0.853, 0.861]} />
        <mesh geometry={nodes.player1Screen.geometry} material={nodes.player1Screen.material} />
        <mesh geometry={nodes.player1Wheel_1.geometry} material={nodes.player1Wheel_1.material} position={[0.388, -0.672, 0.394]} />
        <mesh geometry={nodes.player1Wheel_2.geometry} material={nodes.player1Wheel_2.material} position={[0.388, -0.672, -0.406]} />
        <mesh geometry={nodes.player1Wheel_3.geometry} material={nodes.player1Wheel_3.material} position={[-0.379, -0.672, 0.394]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh geometry={nodes.player1Wheel_4.geometry} material={nodes.player1Wheel_4.material} position={[-0.379, -0.672, -0.406]} rotation={[Math.PI, 0, Math.PI]} />
      </mesh>
      <mesh geometry={nodes.bulletmodel1.geometry} material={nodes.bulletmodel1.material} position={[1.643, 1.862, 1.22]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.coinmodel1.geometry} material={nodes.coinmodel1.material} position={[-2.992, 0.877, 0]} />
      <mesh geometry={nodes.bombmodel1.geometry} material={nodes.bombmodel1.material} position={[-2, 0.6, 3]}>
        <mesh geometry={nodes.bombmodel1belt.geometry} material={nodes.bombmodel1belt.material} />
        <mesh geometry={nodes.bombmodel1head.geometry} material={nodes.bombmodel1head.material} />
      </mesh>
      <mesh geometry={nodes.playermodel2.geometry} material={nodes.playermodel2.material} position={[-5, 1.2, 0]}>
        <mesh geometry={nodes.playerHat.geometry} material={nodes.playerHat.material} position={[0, 0.273, -0.273]} />
        <mesh geometry={nodes.playermodel2Screen.geometry} material={nodes.playermodel2Screen.material} />
      </mesh>
      <mesh geometry={nodes.portal_2.geometry} material={nodes.portal_2.material} position={[-2.007, 1.857, -2.037]}>
        <mesh geometry={nodes.portal_2_glass.geometry} material={nodes.portal_2_glass.material} position={[0, -0.839, 0]} />
      </mesh>
      <mesh geometry={nodes.battery.geometry} material={nodes.battery.material} position={[-8.007, -0.048, -2.037]}>
        <mesh geometry={nodes.batteryHead.geometry} material={nodes.batteryHead.material} position={[0, 1.5, 0]} />
      </mesh>
      <mesh geometry={nodes.bomb.geometry} material={nodes.bomb.material} position={[-9.979, 0.524, -1.998]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.bombScreen.geometry} material={nodes.bombScreen.material} position={[-0.204, 0, 0.569]} rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes.bombScreen2.geometry} material={nodes.bombScreen2.material} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.exit.geometry} material={nodes.exit.material} position={[-5.035, -0.001, -2.287]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.exitdoor.geometry} material={nodes.exitdoor.material} position={[0, 0, -1.178]} />
      </mesh>
      <mesh geometry={nodes.key2.geometry} material={nodes.key2.material} position={[0.913, 3.047, 0.06]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.tree2.geometry} material={nodes.tree2.material} position={[9.978, -0.002, -1.988]} />
      <mesh geometry={nodes.clim.geometry} material={nodes.clim.material} position={[-12, 0, 0]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.climfan.geometry} material={nodes.climfan.material} position={[0.003, 0.796, 0.518]} />
      </mesh>
      <mesh geometry={nodes.exit2.geometry} material={nodes.exit2.material} position={[-10, 0, 0]}>
        <mesh geometry={nodes.exit2shad.geometry} material={nodes.exit2shad.material} position={[0, 1.047, 0]} />
      </mesh>
      <mesh geometry={nodes.barrier.geometry} material={nodes.barrier.material} position={[3, 0.135, -4]}>
        <mesh geometry={nodes.barrierShad.geometry} material={nodes.barrierShad.material} position={[0, 1.048, 0]} />
      </mesh>
      <mesh geometry={nodes.box2.geometry} material={nodes.box2.material} position={[3, 0.605, 0]} />
      <mesh geometry={nodes.mousemob.geometry} material={nodes.mousemob.material} position={[7, 0.047, -4]}>
        <mesh geometry={nodes.mousemobEye.geometry} material={nodes.mousemobEye.material} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/model.glb')
